#! /bin/bash

# jsession by J

# Licensed under the GNU General Public License, version 3; if this was not
# included, you can find it here:
#     http://www.gnu.org/licenses/gpl-3.0.txt

# handle arguments
for arg in $@; do
    case $arg in
    logout)
        signal=TERM
        ;;
    halt)
        signal=USR1
        ;;
    reboot)
        signal=USR2
        ;;
    -a)
        all=1
        ;;
    *)
        echo "error: unknown option '$arg'" 1>&2
        exit 1
        ;;
    esac
done
if [ -z $signal ]; then
    echo "error: expected an argument" 1>&2
    exit 1
fi

# if logging out and got -a, quit all jsessions
if [ -n "$all" ] && [ $signal = TERM ]; then
    pkill jsession
else
    # get this display's jsession PID
    pids=`grep $DISPLAY ~/.jsession/running | cut -d" " -f1 2> /dev/null`
    numpids=`echo $pids | wc -w`
    if [ $numpids -eq 0 ]; then
        echo "error: couldn't determine the current jsession" 1>&2
        exit 2
    fi
    # send signal to first PID that corresponds to a jsession, if any
    for pid in $pids; do
        name=`ps -p $pid -o comm= 2> /dev/null`
        if [ "$name" = jsession ]; then
            # send signal
            kill -$signal $pid
            exit 0
        fi
    done
    # didn't find anything
    echo "error: couldn't determine the current jsession" 1>&2
    exit 2
fi
